// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maagbeaeenzglbdoknmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hYWdiZWFlZW56Z2xiZG9rbm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDU1NzcsImV4cCI6MjA2MTE4MTU3N30.JeKAZKDeJQU7eMQDdr9YPpCm-omUWPN-0BcFcEdQCQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);